# Using COVID-19 Dataset

## DRAFT ONLY

### The content of this Jupyter Notebook does not follow the required format by Sir Neil Romblon. This notebook only aims to explore and test possible actions that could/shall be performed on the given dataset from Our World in Data.

### The dataset contains the cases (new and total), deaths (new and total), vaccinations (new and total), and other demographic values such as country population and population density, GDP per capita, stringency (regarding COVID-19 protocols), etc.

# Initial Importation of Data

In [1]:
#import libraries
import numpy as np
import pandas as pd

In [2]:
#importing csv into dataframe
covid_df = pd.read_csv('covid_july_15.csv')
covid_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102470,ZWE,Africa,Zimbabwe,2021-07-10,66853.0,1787.0,1884.000,2126.0,42.0,38.143,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102471,ZWE,Africa,Zimbabwe,2021-07-11,67765.0,912.0,1898.714,2185.0,59.0,43.857,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102472,ZWE,Africa,Zimbabwe,2021-07-12,70426.0,2661.0,2058.857,2236.0,51.0,46.429,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102473,ZWE,Africa,Zimbabwe,2021-07-13,73271.0,2845.0,2186.857,2274.0,38.0,47.857,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102474,ZWE,Africa,Zimbabwe,2021-07-14,76381.0,3110.0,2307.714,2332.0,58.0,51.286,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN

### Initial Observations (Macro Level)
1. Data is indicated as null/NaN if empty
2. Countries are repeatedly indicated on every day that was recorded.
3. There are some columns with no data available or has data but only to a few countries.

# Content Checking of every Column

## Checking Column for null values and possible unusable values.

In [3]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102475 entries, 0 to 102474
Data columns (total 60 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   iso_code                               102475 non-null  object
 1   continent                              97689 non-null   object
 2   location                               102475 non-null  object
 3   date                                   102475 non-null  object
 4   total_cases                            98594 non-null   float64
 5   new_cases                              98591 non-null   float64
 6   new_cases_smoothed                     97581 non-null   float64
 7   total_deaths                           88371 non-null   float64
 8   new_deaths                             88527 non-null   float64
 9   new_deaths_smoothed                    97581 non-null   float64
 10  total_cases_per_million                98070 non-null   float64
 11  new_cases_per_million                  98067 non-null   float64
 12  new_cases_smoothed_per_million         97062 non-null   float64
 13  total_deaths_per_million               87860 non-null   float64
 14  new_deaths_per_million                 88016 non-null   float64
 15  new_deaths_smoothed_per_million        97062 non-null   float64
 16  reproduction_rate                      82782 non-null   float64
 17  icu_patients                           10688 non-null   float64
 18  icu_patients_per_million               10688 non-null   float64
 19  hosp_patients                          12916 non-null   float64
 20  hosp_patients_per_million              12916 non-null   float64
 21  weekly_icu_admissions                  951 non-null     float64
 22  weekly_icu_admissions_per_million      951 non-null     float64
 23  weekly_hosp_admissions                 1614 non-null    float64
 24  weekly_hosp_admissions_per_million     1614 non-null    float64
 25  new_tests                              45788 non-null   float64
 26  total_tests                            45457 non-null   float64
 27  total_tests_per_thousand               45457 non-null   float64
 28  new_tests_per_thousand                 45788 non-null   float64
 29  new_tests_smoothed                     53305 non-null   float64
 30  new_tests_smoothed_per_thousand        53305 non-null   float64
 31  positive_rate                          49803 non-null   float64
 32  tests_per_case                         49173 non-null   float64
 33  tests_units                            54997 non-null   object
 34  total_vaccinations                     18050 non-null   float64
 35  people_vaccinated                      17196 non-null   float64
 36  people_fully_vaccinated                14334 non-null   float64
 37  new_vaccinations                       15041 non-null   float64
 38  new_vaccinations_smoothed              31499 non-null   float64
 39  total_vaccinations_per_hundred         18050 non-null   float64
 40  people_vaccinated_per_hundred          17196 non-null   float64
 41  people_fully_vaccinated_per_hundred    14334 non-null   float64
 42  new_vaccinations_smoothed_per_million  31499 non-null   float64
 43  stringency_index                       85982 non-null   float64
 44  population                             101817 non-null  float64
 45  population_density                     95179 non-null   float64
 46  median_age                             91455 non-null   float64
 47  aged_65_older                          90429 non-null   float64
 48  aged_70_older                          90950 non-null   float64
 49  gdp_per_capita                         91824 non-null   float64
 50  extreme_poverty                        61921 non-null   float64
 51  cardiovasc_death_rate                  91810 non-null   float64
 52  diabetes_prevalence                    94235 non-null   float64
 53  female_smokers                         71798 non-null   float64
 54  male_smokers                           70751 non-null   float64
 55  handwashing_facilities                 46133 non-null   float64
 56  hospital_beds_per_thousand             83618 non-null   float64
 57  life_expectancy                        97312 non-null   float64
 58  human_development_index                91948 non-null   float64
 59  excess_mortality                       3624 non-null    float64
dtypes: float64(55), object(5)
memory usage: 46.9+ MB

### Suggestion to remove due to it being unnecessary:
1. new_cases_smoothed
2. new_deaths_smoothed
3. total_cases_per_million
4. new_cases_per_million
5. new_cases_smoothed_per_million
6. total_deaths_per_million
7. new_deaths_per_million
8. new_deaths_smoothed_per_million
9. reproduction_rate
10. icu_patients
11. icu_patients_per_million
12. hosp_patients
13. hosp_patients_per_million
14. weekly_icu_admissions
15. weekly_icu_admissions_per_million
16. weekly_hosp_admissions
17. weekly_hosp_admissions_per_million
18. female_smokers
19. male_smokers
20. excess_mortality
21. median_age
22. aged_65_older
23. aged_70_older
24. handwashing_facilities
25. hospital_beds_per_thousand
26. population_density
27. median_age
28. total_vaccinations_per_hundred
29. people_vaccinated_per_hundred
30. people_fully_vaccinated_per_hundred
31. new_vaccinations_smoothed_per_million

In [4]:
#deleting columns
#source: https://pythonexamples.org/pandas-dataframe-delete-column/

covid_df = covid_df.drop(columns=['new_cases_smoothed','new_deaths_smoothed','total_cases_per_million','new_cases_per_million','new_cases_smoothed_per_million'
                                  ,'total_deaths_per_million','new_deaths_per_million','new_deaths_smoothed_per_million','reproduction_rate','icu_patients'
                                  ,'icu_patients_per_million','hosp_patients','hosp_patients_per_million','weekly_icu_admissions','weekly_icu_admissions_per_million'
                                  ,'weekly_hosp_admissions_per_million','female_smokers','male_smokers','excess_mortality','median_age','aged_65_older','aged_70_older'
                                  ,'handwashing_facilities','hospital_beds_per_thousand','population_density','median_age','total_vaccinations_per_hundred'
                                  ,'people_vaccinated_per_hundred','people_fully_vaccinated_per_hundred','new_vaccinations_smoothed_per_million'])
covid_df.info() #rechecking changes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102475 entries, 0 to 102474
Data columns (total 31 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   iso_code                         102475 non-null  object
 1   continent                        97689 non-null   object
 2   location                         102475 non-null  object
 3   date                             102475 non-null  object
 4   total_cases                      98594 non-null   float64
 5   new_cases                        98591 non-null   float64
 6   total_deaths                     88371 non-null   float64
 7   new_deaths                       88527 non-null   float64
 8   weekly_hosp_admissions           1614 non-null    float64
 9   new_tests                        45788 non-null   float64
 10  total_tests                      45457 non-null   float64
 11  total_tests_per_thousand         45457 non-null   float64
 12  new_tests_per_thousand           45788 non-null   float64
 13  new_tests_smoothed               53305 non-null   float64
 14  new_tests_smoothed_per_thousand  53305 non-null   float64
 15  positive_rate                    49803 non-null   float64
 16  tests_per_case                   49173 non-null   float64
 17  tests_units                      54997 non-null   object
 18  total_vaccinations               18050 non-null   float64
 19  people_vaccinated                17196 non-null   float64
 20  people_fully_vaccinated          14334 non-null   float64
 21  new_vaccinations                 15041 non-null   float64
 22  new_vaccinations_smoothed        31499 non-null   float64
 23  stringency_index                 85982 non-null   float64
 24  population                       101817 non-null  float64
 25  gdp_per_capita                   91824 non-null   float64
 26  extreme_poverty                  61921 non-null   float64
 27  cardiovasc_death_rate            91810 non-null   float64
 28  diabetes_prevalence              94235 non-null   float64
 29  life_expectancy                  97312 non-null   float64
 30  human_development_index          91948 non-null   float64
dtypes: float64(26), object(5)
memory usage: 24.2+ MB

## Checking if there are how many null values are there on each column, if it exists.

In [5]:
nullvalues = covid_df.columns[covid_df.isnull().any()].tolist() 
covid_df[nullvalues].sum()

total_cases                        1.097622e+11
new_cases                          5.972300e+08
total_deaths                       2.636557e+09
new_deaths                         1.291616e+07
weekly_hosp_admissions             5.543137e+06
new_tests                          2.232705e+09
total_tests                        3.705594e+11
total_tests_per_thousand           1.492585e+07
new_tests_per_thousand             9.899525e+04
new_tests_smoothed                 2.465038e+09
new_tests_smoothed_per_thousand    1.104295e+05
positive_rate                      4.396642e+03
tests_per_case                     8.154874e+06
total_vaccinations                 6.532460e+11
people_vaccinated                  3.439826e+11
people_fully_vaccinated            1.598590e+11
new_vaccinations                   1.065705e+10
new_vaccinations_smoothed          1.075437e+10
stringency_index                   4.997160e+06
population                         1.265439e+13
gdp_per_capita                     1.770682e+09
extreme_poverty                    8.309423e+05
cardiovasc_death_rate              2.374281e+07
diabetes_prevalence                7.480864e+05
life_expectancy                    7.127047e+06
human_development_index            6.686700e+04
dtype: float64