# Using COVID-19 Dataset

## DRAFT ONLY

### The content of this Jupyter Notebook does not follow the required format by Sir Neil Romblon. This notebook only aims to explore and test possible actions that could/shall be performed on the given dataset from Our World in Data.

### The dataset contains the cases (new and total), deaths (new and total), vaccinations (new and total), and other demographic values such as country population and population density, GDP per capita, stringency (regarding COVID-19 protocols), etc.

# Initial Importation of Data

In [1]:
#import libraries
import numpy as np
import pandas as pd

#importing csv into dataframe
covid_df = pd.read_csv('COVID_7_15.csv')
covid_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102470,ZWE,Africa,Zimbabwe,2021-07-10,66853.0,1787.0,1884.000,2126.0,42.0,38.143,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102471,ZWE,Africa,Zimbabwe,2021-07-11,67765.0,912.0,1898.714,2185.0,59.0,43.857,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102472,ZWE,Africa,Zimbabwe,2021-07-12,70426.0,2661.0,2058.857,2236.0,51.0,46.429,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102473,ZWE,Africa,Zimbabwe,2021-07-13,73271.0,2845.0,2186.857,2274.0,38.0,47.857,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN
102474,ZWE,Africa,Zimbabwe,2021-07-14,76381.0,3110.0,2307.714,2332.0,58.0,51.286,...,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571,NaN

### Initial Observations (Macro Level)
1. Data is indicated as null/NaN if empty
2. Countries are repeatedly indicated on every day that was recorded.
3. There are some columns with no data available or has data but only to a few countries.

# Content Checking of every Column

## Checking Column for null values and possible unusable values.

In [2]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102475 entries, 0 to 102474
Data columns (total 60 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   iso_code                               102475 non-null  object
 1   continent                              97689 non-null   object
 2   location                               102475 non-null  object
 3   date                                   102475 non-null  object
 4   total_cases                            98594 non-null   float64
 5   new_cases                              98591 non-null   float64
 6   new_cases_smoothed                     97581 non-null   float64
 7   total_deaths                           88371 non-null   float64
 8   new_deaths                             88527 non-null   float64
 9   new_deaths_smoothed                    97581 non-null   float64
 10  total_cases_per_million                98070 non-null   float64
 11  new_cases_per_million                  98067 non-null   float64
 12  new_cases_smoothed_per_million         97062 non-null   float64
 13  total_deaths_per_million               87860 non-null   float64
 14  new_deaths_per_million                 88016 non-null   float64
 15  new_deaths_smoothed_per_million        97062 non-null   float64
 16  reproduction_rate                      82782 non-null   float64
 17  icu_patients                           10688 non-null   float64
 18  icu_patients_per_million               10688 non-null   float64
 19  hosp_patients                          12916 non-null   float64
 20  hosp_patients_per_million              12916 non-null   float64
 21  weekly_icu_admissions                  951 non-null     float64
 22  weekly_icu_admissions_per_million      951 non-null     float64
 23  weekly_hosp_admissions                 1614 non-null    float64
 24  weekly_hosp_admissions_per_million     1614 non-null    float64
 25  new_tests                              45788 non-null   float64
 26  total_tests                            45457 non-null   float64
 27  total_tests_per_thousand               45457 non-null   float64
 28  new_tests_per_thousand                 45788 non-null   float64
 29  new_tests_smoothed                     53305 non-null   float64
 30  new_tests_smoothed_per_thousand        53305 non-null   float64
 31  positive_rate                          49803 non-null   float64
 32  tests_per_case                         49173 non-null   float64
 33  tests_units                            54997 non-null   object
 34  total_vaccinations                     18050 non-null   float64
 35  people_vaccinated                      17196 non-null   float64
 36  people_fully_vaccinated                14334 non-null   float64
 37  new_vaccinations                       15041 non-null   float64
 38  new_vaccinations_smoothed              31499 non-null   float64
 39  total_vaccinations_per_hundred         18050 non-null   float64
 40  people_vaccinated_per_hundred          17196 non-null   float64
 41  people_fully_vaccinated_per_hundred    14334 non-null   float64
 42  new_vaccinations_smoothed_per_million  31499 non-null   float64
 43  stringency_index                       85982 non-null   float64
 44  population                             101817 non-null  float64
 45  population_density                     95179 non-null   float64
 46  median_age                             91455 non-null   float64
 47  aged_65_older                          90429 non-null   float64
 48  aged_70_older                          90950 non-null   float64
 49  gdp_per_capita                         91824 non-null   float64
 50  extreme_poverty                        61921 non-null   float64
 51  cardiovasc_death_rate                  91810 non-null   float64
 52  diabetes_prevalence                    94235 non-null   float64
 53  female_smokers                         71798 non-null   float64
 54  male_smokers                           70751 non-null   float64
 55  handwashing_facilities                 46133 non-null   float64
 56  hospital_beds_per_thousand             83618 non-null   float64
 57  life_expectancy                        97312 non-null   float64
 58  human_development_index                91948 non-null   float64
 59  excess_mortality                       3624 non-null    float64
dtypes: float64(55), object(5)
memory usage: 46.9+ MB

### Suggestion to remove due to it being unnecessary:
1. new_cases_smoothed
2. new_deaths_smoothed
3. total_cases_per_million
4. new_cases_per_million
5. new_cases_smoothed_per_million
6. total_deaths_per_million
7. new_deaths_per_million
8. new_deaths_smoothed_per_million
9. reproduction_rate
10. icu_patients
11. icu_patients_per_million
12. hosp_patients
13. hosp_patients_per_million
14. weekly_icu_admissions
15. weekly_icu_admissions_per_million
16. weekly_hosp_admissions
17. weekly_hosp_admissions_per_million
18. female_smokers
19. male_smokers
20. excess_mortality
21. median_age
22. aged_65_older
23. aged_70_older
24. handwashing_facilities
25. hospital_beds_per_thousand
26. population_density
27. median_age
28. total_vaccinations_per_hundred
29. people_vaccinated_per_hundred
30. people_fully_vaccinated_per_hundred
31. new_vaccinations_smoothed_per_million
32. new_vaccinations_smoothed
33. extreme_poverty
34. cardiovasc_death_rate
35. diabetes_prevalence
36. weekly_hosp_admissions
37. new_tests
38. total_tests
39. total_tests_per_thousand
40. new_tests_per_thousand
41. new_tests_smoothed
42. new_tests_smoothed_per_thousand
43. tests_per_case
44. tests_units 

Some of the reasons for suggestion of removal include:
1. High variance of data
2. Might be unnecessary to the goal questions.
3. Columns having pre-treated values (smoothing and per thousand/million unit)
4. High number of null values

In [3]:
#deleting columns
#source: https://pythonexamples.org/pandas-dataframe-delete-column/

#COLUMN FLAGS
identifiers = ['iso_code','continent','location','date']
toDrop = ['new_cases_smoothed','new_deaths_smoothed','total_cases_per_million','new_cases_per_million','new_cases_smoothed_per_million'
          ,'total_deaths_per_million','new_deaths_per_million','new_deaths_smoothed_per_million','reproduction_rate','icu_patients'
          ,'icu_patients_per_million','hosp_patients','hosp_patients_per_million','weekly_icu_admissions','weekly_icu_admissions_per_million'
          ,'weekly_hosp_admissions_per_million','female_smokers','male_smokers','excess_mortality','median_age','aged_65_older','aged_70_older'
          ,'handwashing_facilities','hospital_beds_per_thousand','population_density','median_age','total_vaccinations_per_hundred'
          ,'people_vaccinated_per_hundred','people_fully_vaccinated_per_hundred','new_vaccinations_smoothed_per_million'
          ,'new_vaccinations_smoothed','extreme_poverty','cardiovasc_death_rate','diabetes_prevalence', 'weekly_hosp_admissions'
          ,'new_tests','total_tests','total_tests_per_thousand','new_tests_per_thousand','new_tests_smoothed'
          ,'new_tests_smoothed_per_thousand','tests_per_case','tests_units','positive_rate','life_expectancy','human_development_index']
toRetainData = ['total_cases','new_cases','total_deaths','new_deaths','total_vaccinations',
                'people_vaccinated','people_fully_vaccinated','new_vaccinations','stringency_index',
                'population','gdp_per_capita']

#data cleanup - column removal
covid_df = covid_df.drop(columns=toDrop)
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102475 entries, 0 to 102474
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   iso_code                 102475 non-null  object
 1   continent                97689 non-null   object
 2   location                 102475 non-null  object
 3   date                     102475 non-null  object
 4   total_cases              98594 non-null   float64
 5   new_cases                98591 non-null   float64
 6   total_deaths             88371 non-null   float64
 7   new_deaths               88527 non-null   float64
 8   total_vaccinations       18050 non-null   float64
 9   people_vaccinated        17196 non-null   float64
 10  people_fully_vaccinated  14334 non-null   float64
 11  new_vaccinations         15041 non-null   float64
 12  stringency_index         85982 non-null   float64
 13  population               101817 non-null  float64
 14  gdp_per_capita           91824 non-null   float64
dtypes: float64(11), object(4)
memory usage: 11.7+ MB

Based on the preview, the columns that have NaN values are:
0. total_cases (if the country had a case on a later date; needed for data alignment)
1. new_cases (if the country had a case on a later date; needed for data alignment)
2. total_deaths
3. new_deaths
4. total_vaccinations
5. people-vaccinated
6. people_fully_vaccinated
7. new_vaccinations
8. stringency_index
    
However, replacing any null valued integer with 0 will affect aggregation operations like the mean and other statistical operations.

## Filtering Countries from Dataframe
### Based on our goal objectives for the data, we only aim to make use of the following countries/iso_codes in the given dataset.
1. ASEAN Member States (10 Nations)
2. OWID_WRL - World (OWID Notation)

In [4]:
covid_df['iso_code'].unique()

array(['AFG', 'OWID_AFR', 'ALB', 'DZA', 'AND', 'AGO', 'AIA', 'ATG', 'ARG',
       'ARM', 'ABW', 'OWID_ASI', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD',
       'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BES',
       'BIH', 'BWA', 'BRA', 'VGB', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM',
       'CMR', 'CAN', 'CPV', 'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'COL',
       'COM', 'COG', 'COK', 'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP',
       'CZE', 'COD', 'DNK', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'SLV',
       'GNQ', 'ERI', 'EST', 'SWZ', 'ETH', 'OWID_EUR', 'OWID_EUN', 'FRO',
       'FLK', 'FJI', 'FIN', 'FRA', 'PYF', 'GAB', 'GMB', 'GEO', 'DEU',
       'GHA', 'GIB', 'GRC', 'GRL', 'GRD', 'GTM', 'GGY', 'GIN', 'GNB',
       'GUY', 'HTI', 'HND', 'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'OWID_INT',
       'IRN', 'IRQ', 'IRL', 'IMN', 'ISR', 'ITA', 'JAM', 'JPN', 'JEY',
       'JOR', 'KAZ', 'KEN', 'KIR', 'OWID_KOS', 'KWT', 'KGZ', 'LAO', 'LVA',
       'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU', 'LUX', 'MAC', 'MDG',
       'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MHL', 'MRT', 'MUS', 'MEX',
       'FSM', 'MDA', 'MCO', 'MNG', 'MNE', 'MSR', 'MAR', 'MOZ', 'MMR',
       'NAM', 'NRU', 'NPL', 'NLD', 'NCL', 'NZL', 'NIC', 'NER', 'NGA',
       'NIU', 'OWID_NAM', 'MKD', 'OWID_CYN', 'NOR', 'OWID_OCE', 'OMN',
       'PAK', 'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'PCN', 'POL',
       'PRT', 'QAT', 'ROU', 'RUS', 'RWA', 'SHN', 'KNA', 'LCA', 'VCT',
       'WSM', 'SMR', 'STP', 'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP',
       'SXM', 'SVK', 'SVN', 'SLB', 'SOM', 'ZAF', 'OWID_SAM', 'KOR', 'SSD',
       'ESP', 'LKA', 'SDN', 'SUR', 'SWE', 'CHE', 'SYR', 'TWN', 'TJK',
       'TZA', 'THA', 'TLS', 'TGO', 'TON', 'TTO', 'TUN', 'TUR', 'TKM',
       'TCA', 'TUV', 'UGA', 'UKR', 'ARE', 'GBR', 'USA', 'URY', 'UZB',
       'VUT', 'VAT', 'VEN', 'VNM', 'WLF', 'OWID_WRL', 'YEM', 'ZMB', 'ZWE'],
      dtype=object)

In [5]:
country = ['PHL','BRN','KHM','IDN','SGP','LAO','THA','MYS','MMR','VNM','OWID_WRL']
covid_df = covid_df[covid_df['iso_code'].str.contains('PHL|BRN|KHM|IDN|SGP|LAO|THA|MYS|MMR|VNM|OWID_WRL',regex=True)]
covid_df.sort_values(by=['iso_code','date'])
covid_df['iso_code'].unique()

array(['BRN', 'KHM', 'IDN', 'LAO', 'MYS', 'MMR', 'PHL', 'SGP', 'THA',
       'VNM', 'OWID_WRL'], dtype=object)

## Checking if there are how many null values are there on each column, if it exists.

In [6]:
nullvalues = covid_df.columns[covid_df.isnull().any()].tolist()
covid_df[nullvalues].sum()

total_cases                3.524906e+10
new_cases                  1.936431e+08
total_deaths               8.402160e+08
new_deaths                 4.168321e+06
total_vaccinations         2.187899e+11
people_vaccinated          1.222525e+11
people_fully_vaccinated    5.567553e+10
new_vaccinations           3.627646e+09
stringency_index           2.934682e+05
dtype: float64

## Checking content of each column.

In [7]:
#Col: iso_code
print("iso_code:",covid_df['iso_code'].unique())
#any value that contains 'OWID' shall be removed as it is a cummulative value per continent
#or it could be used to simplify value aggregation for worldwide baseline data


#Col: continent
#covid_df['continent'].isnull().any() #will state that there are null (as nan) values
covid_df.loc[covid_df['continent'].isnull(),'continent'] = 'None' #replace null with 'None'
print("continent:",covid_df['continent'].unique())
#covid_df['continent'].isnull().any()

#Col: location
# Might remove due to being a duplicate (i.e. elongated version) of the content in iso_code
print("location:",covid_df['location'].unique()) #uncomment to list all values
#Sidenote: any iso_code that contain 'OWID' has a continent==NaN

#Col: date
print("null date:", covid_df['date'].isnull().any())
#luckily on dates there are no null values

iso_code: ['BRN' 'KHM' 'IDN' 'LAO' 'MYS' 'MMR' 'PHL' 'SGP' 'THA' 'VNM' 'OWID_WRL']
continent: ['Asia' 'None']
location: ['Brunei' 'Cambodia' 'Indonesia' 'Laos' 'Malaysia' 'Myanmar' 'Philippines'
 'Singapore' 'Thailand' 'Vietnam' 'World']
null date: False

## Earliest and Latest Dates

In [8]:
date_values = covid_df['date'].unique()
date_values = np.sort(date_values,kind='mergesort')
dateCount = date_values.size
print("dateCount:",dateCount,"\n")
print("earliest:",date_values[0])
print("latest (valid):",date_values[len(date_values)-1])
#the latest possible data maybe incomplete, so to be safe let's just adjust it to the day before the latest date entered

dateCount: 558

earliest: 2020-01-04
latest (valid): 2021-07-14

## Separating Countries to Individual Dataframes

In [10]:
#countries to individual dataframes
world_df = covid_df[covid_df['iso_code']=='OWID_WRL'] #World
phl_df = covid_df[covid_df['iso_code']=='PHL'] #Philippines
brn_df = covid_df[covid_df['iso_code']=='BRN'] #Brunei
khm_df = covid_df[covid_df['iso_code']=='KHM'] #Cambodia
idn_df = covid_df[covid_df['iso_code']=='IDN'] #Indonesia
sgp_df = covid_df[covid_df['iso_code']=='SGP'] #Singapore
lao_df = covid_df[covid_df['iso_code']=='LAO'] #Lao PDR
tha_df = covid_df[covid_df['iso_code']=='THA'] #Thailand
mys_df = covid_df[covid_df['iso_code']=='MYS'] #Malaysia
mmr_df = covid_df[covid_df['iso_code']=='MMR'] #Myanmar
vnm_df = covid_df[covid_df['iso_code']=='VNM'] #Vietnam

#compiled (but separated) dataframes
compiled_str = ['phl_df','brn_df','khm_df','idn_df','sgp_df','lao_df','tha_df','mys_df','mmr_df','vnm_df','world_df']
compiled = [phl_df,brn_df,khm_df,idn_df,sgp_df,lao_df,tha_df,mys_df,mmr_df,vnm_df,world_df] #lists of lists, hehehe

#number of observations and sorting by 'date'
print("entries/observations/daysWithCOVID per country:")
for i in range(len(compiled)):
    print(compiled_str[i],':',compiled[i].shape[0])
    compiled[i].sort_values(by='date',kind='mergesort')
print("")

print("earliest records by country: ")
for i in range(len(compiled)):
    print(compiled_str[i],":",compiled[i]['date'].iloc[0])
print("\n")

print("latest records by country: ")
for i in range(len(compiled)):
    print(compiled_str[i],":",compiled[i]['date'].iloc[compiled[i].shape[0]]-1)

entries/observations/daysWithCOVID per country:
phl_df : 532
brn_df : 493
khm_df : 535
idn_df : 500
sgp_df : 539
lao_df : 478
tha_df : 558
mys_df : 537
mmr_df : 475
vnm_df : 539
world_df : 540

earliest records by country:
phl_df : 2020-01-30
brn_df : 2020-03-09
khm_df : 2020-01-27
idn_df : 2020-03-02
sgp_df : 2020-01-23
lao_df : 2020-03-24
tha_df : 2020-01-04
mys_df : 2020-01-25
mmr_df : 2020-03-27
vnm_df : 2020-01-23
world_df : 2020-01-22


latest records by country:

IndexError: single positional indexer is out-of-bounds

In [ ]:
#create list of months
month_list = [] #make use of this
year = 2020
mo = 0
for i in range(19):
    if(mo==12):
        year = year + 1
        mo = 1
    else:
        mo = mo + 1
    val = str(year)+'-'+str(mo)+'-'+'01'
    month_list.append(val)
print("dates to focus:","\n",month_list)